# Generated by Django 4.1.1 on 2022-11-25 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bitatu', '0003_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='breakdown',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='country',
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='main',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blogs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
