# Generated by Django 4.1.1 on 2022-11-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitatu', '0007_rename_exp_testimonial_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='phone',
        ),
    ]
