# Generated by Django 4.1.1 on 2022-11-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitatu', '0008_remove_userregistration_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userregistration',
        ),
    ]
