# Generated by Django 4.1.1 on 2022-11-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitatu', '0010_userregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='password2',
            field=models.CharField(default=models.CharField(max_length=20), max_length=20),
        ),
    ]
