# Generated by Django 4.1.1 on 2022-11-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitatu', '0011_userregistration_password2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdata',
        ),
    ]
