# Generated by Django 4.1.1 on 2022-11-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitatu', '0012_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('profession', models.CharField(max_length=50, null=True)),
                ('position_in_betatu', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
