# Generated by Django 4.1.1 on 2022-12-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitatu', '0014_alter_team_position_in_betatu_alter_team_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('about', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
