# Generated by Django 4.1.1 on 2022-12-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitatu', '0015_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='date_of_birth',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='educational_background',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='profession',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
