# Generated by Django 4.1.1 on 2022-12-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitatu', '0017_user_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userregistration',
        ),
    ]
